
# 竞赛任务参数

# 运动速度 m/s
linear_x: 0.4
# 转向速度 rad/s
anglular_z: 3
# 速度发布的话题名
cmd_vel_topic: "/cmd_vel"
# 发布机械臂指令的话题名
cmd_arm_topic: "/arm_cmd"

# 给定速度之后运动的时长和停止的时长
# 共有7组可单独设置的参数，每个行动可根据任务选择一组
goA_along_time: [[2.85,5.0],
                [1.63,5.0],
                [1.63,5.0],
                [7.65,5.0],
                [5.8,10.0],
                [6.7,10.0],
                [2.1,10.0]]

goB_along_time: [[1.0,5.0],
                [1.25,10.0],
                [1.0,5.0],
                [4.4,10.0],
                [3.8,10.0],
                [1.5,30.0],
                [1.0,30.0]]

goC_along_time: [[1.1,5.0],
                [7.82,5.0],
                [8.0,5.0],
                [6.35,5.0],
                [0.88,10.0],
                [1.0,30.0],
                [0.625,30.0]]
# A任务参数
task_A_go_along: [0,1,2,1,3]
# B任务参数
task_B_go_along: [1,1,1,1,1,0,3,4,0]
# C任务参数
task_C_go_along: [0,1,4,0,2,3]
forward_time: 1.66
backward_time: 1.66
forward_small_time: 1.57
backward_small_time: 1.6
forward_big_time: 2.32
turn_left_time: 1.1
turn_right_time: 1.1
